all : SequentialCollisions ParallelCollisions ParallelCollisionsFS ParallelCollisionsBarrier

SequentialCollisions :
	javac SequentialCollisions.java

ParallelCollisions :
	javac ParallelCollisions.java

ParallelCollisionsFS :
	javac ParallelCollisionsFS.java

ParallelCollisionsBarrier :
	javac ParallelCollisionsBarrier.java
