package network;

/**
 * Enumeration defines message type for Packet objects passed between
 * client.Client and server.Server.
 * 
 * @author Daniel Eisenberg
 */
public enum Type {
	SAY, TELL, OOC, PARTY, SOCIAL, MOVE, SERVER_BROADCAST, LOGIN, LOGOUT, NEW_ACCOUNT, ERROR, SERVER_MESSAGE, CHARACTER_SELECT, DELETE_CHARACTER, CREATE_CHARACTER, SHUTDOWN, RESTART, KICK, BAN, BAN_IP, INVITE, LEAVE_PARTY, OUTPUT_QUEUE_POISON_PILL, WHO, MAKE_MODERATOR, INVENTORY, GIVE, GET, USE, LOOK, DROP, STATUS, LOGIN_SUCCESS, JOIN, UNINVITE, MAKE_LEADER, META_DATA, ATTACK, CAST, EQUIP, UNEQUIP, ABILITIES, ENTER, EXIT;
}
