# makefile for prog11
# Daniel Eisenberg
# CSc 352 Fall 2011, Program #11

# Macros

    CC          = gcc           # compiler

# Targets

prog11:     orthogonallist.h orthogonallist.c
	$(CC) -o prog11 orthogonallist.c prog11.c
